# This is a Kubernetes Deployment manifest for deploying an application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: argo-app-container
          image: nginx:latest
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
