apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
  namespace: argocd
spec:
  selector:
    app: argo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007