apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
  namespace: argocd
spec:
  selector:
    app: argo-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 30008
